language: node_js
node_js:
  - '10'
  - '8'
cache: yarn
before_script:
  - git remote set-url origin
    https://${GITHUB_TOKEN}@github.com/sinnerschrader/feature-hub.git
  - git config --global user.email "feature-hub@sinnerschrader.com"
  - git config --global user.name "Feature Hub CI"
  - npm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
script:
  - ./scripts/ci/test.sh
deploy:
  provider: script
  script: scripts/ci/release.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = api
    node: '10'
env:
  global:
    - secure: 'WhmerwQ4P67BnUHm1a+aQtwUClQGtsCe5mqE6/l+vcSYjcgaPSjfCXWpeA0wgvLUMsSIngi5HTwx2U0ZagyywDeHORNGmPNk22bvttioDGIpWhypL2WEriRF1KcacJzwSIF/J7J7UE+SQmLUHmGh2PbykwS4uFCiZ/1fgpw9wGkPkQTOCB0ebvgHoBP4ad+Z94RfHJBaSk615Dg/L2m3L+IQewV7gFVE7l/UoO22+aJnbn00BlDrwMXt4neKJt5xhstG6aFIjakYvek6tXrd6um1T4MftolEFpfgr19tujGAHVG70O3m5WOTdBYlfHNo9ZUQ8g0z//W8yajSAlBQj+TcFDyt9x9adMvZilh+OzCrJbhJV0BqSpF+l4ngO5o1KpWx3J6K7KUX41SONEusw/XBJNz1DYf2uROWagVxkZe0cWek64bS+HBlHV1fJd6w9infrSWwZgECGcJtQwNQN4wasDRE5vc07aMlYbmshefh1o30C4478X7nGJd1Rb3oaSxp/oFGCORxQmT71XyINe2hAXriTJLLzhz4K43cJb/H/9+J8ldAqwpmhsjvtITF+1zswu6X3TR/Q9yQ9LUmL9SuVMsRehcMYV+qJ9bWNOmJc0ZhOL9NqGBWqjpI2Z+CSy1M0Nc4xvmxhETVY8/mafQLYKXQNi+mGuJUA5ZIaEg='
    - secure: 'lm4sjUkdsT5Teg2mt0TS+sYXMG8rBWpxa9g8Yf3tuZLmHSdXhx6LZr2GpsNJymPGHzk4G7CFvWvBy8SgS6McSQKdzsCRfWFiKfrKSjPa6ub761Ofbzj8ZNqtudwxkJdairBnGerI9F9cc30r+/BCTEibqkWHadIV+kaIfAhJVVrdEdz14j5+1cy2NqSBpqE9jCijlkiMcQcrhKpPx6bNzQUeb0MSlyCuPfWdN4/LeU1Q3Xo6qXlp/OzCYJzZVE+67QdN0eMnPwJjnIWsWywZKkFJtK9cnnTGFTK32+txgHQpo6YZqJFO27S0CpKUPUyZCN2Ym7tQws7qVeG2RvF73WLjTD8xLhFHliET70tm5zlQ+2hGQxm2klmBkUYYuthAqDFPaC4bV8v1aBAgZ2dTBgekdEOHzCSZXjpaCEx8YVNP/UfdjLc580d12TvI7egxxIKltjb4CV8bDMChQ8krdcc1C1qEr+HG0cIpmZDvQk1RkPzbuubXRFK3C6i9ce55p0qOP546FMNt8tyMratDsriinGPJx+okvJP8+3oZDNCRV3/H62a4nhmkF1iZGm4wSKpqvDMRztLNU5V2T5YxLv3Qr0CmPKsAuqD5Svu7gjCzSBF+MGJSTCxyztEl8isSl04wnwvKwK2CuR402RURjEMVgcQ+jJl2nELhrUURNKw='
